import Home from "./pages/home/Home"

export const metadata = {
  title: 'SD-distribuidora',
  description: 'Generated by Next.js',
}

export default function Layout() {
  return (
        <Home/>
  )
}
